action_id: trunk-upgrade-available
date: 2023-07-28 14:07:17
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1690553237
full_timestamp:
  nanos: 5505000
  seconds: 1690553237
trunk_version: 1.13.0
