action_id: trunk-upgrade-available
date: 2023-07-27 21:48:24
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1690494504
full_timestamp:
  nanos: 276158000
  seconds: 1690494504
trunk_version: 1.13.0
