action_id: trunk-share-with-everyone
date: 2023-07-28 01:59:19
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1690509559
full_timestamp:
  nanos: 50253000
  seconds: 1690509559
trunk_version: 1.13.0
