action_id: trunk-cache-prune
date: 2023-07-30 09:28:12
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1690709292
full_timestamp:
  nanos: 493455000
  seconds: 1690709292
trunk_version: 1.13.0
