action_id: trunk-cache-prune
date: 2023-07-29 01:02:18
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1690592538
full_timestamp:
  nanos: 7978000
  seconds: 1690592538
trunk_version: 1.13.0
