action_id: trunk-single-player-auto-upgrade
date: 2023-07-29 02:02:17
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1690596137
full_timestamp:
  nanos: 768871000
  seconds: 1690596137
trunk_version: 1.13.0
